name: riboflow
channels:
  - conda-forge
  - bioconda
dependencies:
  - nextflow=26.04.2
  - openjdk=23.0.2
  - umicollapse=1.1.0
  - python=3.12.13
  - samtools=1.23
  - pigz=2.8
  - fastqc=0.12.1
  - setuptools=82.0.1
  - pip=26.1.1
  - numpy=1.26.4
  - pandas=3.0.3
  - scipy=1.17.1
  - matplotlib=3.10.9
  - bowtie2=2.5.5
  - star=2.7.11b
  - bx-python=0.14.0
  - pysam=0.24.0
  - bedtools=2.31.1
  - cutadapt=5.2
  - deeptools=3.5.5
  - ucsc-bedgraphtobigwig=482
  - umi_tools=1.1.6
  - pip:
    - git+https://github.com/ribosomeprofiling/ribopy.git@380421e202f25a9829b36c1c1d5a8bf333d9188f
    - git+https://github.com/ribosomeprofiling/RFCommands.git@a8ba526bcaebacf035dd1412915708d44065f1d9
